In [1]:
import numpy as np 


In [2]:
byte1= np.array([0x12, 0xe3, 0x9b])
byte2 = np.array([0x12, 0xe3, 0x9c])


In [3]:
v = byte1^byte2
v1 = np.array (v,dtype = np.uint8)
v1

array([0, 0, 7], dtype=uint8)

In [4]:
z = np.unpackbits(v1)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1], dtype=uint8)

In [5]:
a = sum(z)
a

3

# TEST Längenanpassung

In [6]:
test_byte=np.array([31, 53] + [0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])
test_byte
vlen= 10 

In [7]:
len(test_byte)

10

In [12]:
inp= ([31, 53,0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3]+[30, 53,0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])
len(inp)

20

In [13]:
v = test_byte^inp[:vlen]
v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
for i in range(1,10):
    v = test_byte^inp[:vlen]
    print(v)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
