In [1]:
import numpy as np 


In [2]:
byte1= np.array([0x12, 0xe3, 0x9b])
byte2 = np.array([0x12, 0xe3, 0x9c])


In [3]:
v = byte1^byte2
v1 = np.array (v,dtype = np.uint8)
v1

array([0, 0, 7], dtype=uint8)

In [4]:
z = np.unpackbits(v1)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1], dtype=uint8)

In [5]:
a = sum(z)
a

3

# TEST Längenanpassung

In [6]:
test_byte=np.array([31, 53] + [0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])
test_byte
vlen= 10 

In [7]:
len(test_byte)

10

In [8]:
inp= ([31, 53,0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3]+[30, 53,0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])
len(inp)

20

In [9]:
v = test_byte^inp[:vlen]
v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
for i in range(1,10):
    v = test_byte^inp[:vlen]
    print(v)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


# Test meister Wert 


In [24]:
inp = ([31, 53,0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])
#inp[1] = ([31, 53,0x12, 0xe5, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])
#inp[2] = ([31, 53,0x13, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])

vgl = ([31, 53] + [0x12, 0xe3, 0x9b, 0xee, 0x84, 0x23, 0x41, 0xf3])


print(f"Length: {len(inp)}")
print(f"Inp_vector:{inp}")
        
for i in inp:
    i = np.array(i, dtype=np.uint8)
    v = np.array(vgl, dtype=np.uint8) ^ i
    ber = sum(np.unpackbits(v))

    trueber = ber - 32
    if trueber < 0:
        trueber = 0
    print(f"BER {trueber} in Paket {i}")

    #print(f"max BER {np.max(trueber)} in Paket {i}")
        
    #self.send(self.encode(trueber))

Length: 10
Inp_vector:[31, 53, 18, 227, 155, 238, 132, 35, 65, 243]
BER 6 in Paket 31
BER 6 in Paket 53
BER 4 in Paket 18
BER 2 in Paket 227
BER 4 in Paket 155
BER 12 in Paket 238
BER 10 in Paket 132
BER 0 in Paket 35
BER 6 in Paket 65
BER 2 in Paket 243
