In [1]:
import numpy as np 


In [2]:
byte1= np.array([0x12, 0xe3, 0x9b])
byte2 = np.array([0x12, 0xe3, 0x9c])
b1 = np.array([0,0])
b2 = np.array([0,1])
b1
b2

array([0, 1])

In [6]:
v = byte1^byte2
v1 = np.array (v,dtype = np.uint8)
print(v1)
v2 = b1^b2
v2 = np.array (v2,dtype = np.uint8)
v2

[0 0 7]


array([0, 1], dtype=uint8)

In [7]:
z = np.unpackbits(v1)
print(z)
z1 = np.unpackbits(v2)
z1

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=uint8)

In [5]:
a = sum(z)
a

3